/*
 * Generated by Rohr Engine, then extended with developer-owned gameplay.
 * This file is not covered by Rohr Engine's LGPL-3.0-only license.
 */

#include "project_viewports.h"

#include <math.h>
#include <stdio.h>

#define PLAYER_CONTACT_LIMIT 32

static const float player_move_force = 7500.0f;
static const float player_jump_force = 250000.0f;
static const float player_horizontal_speed_maximum = 260.0f;
static const float player_vertical_speed_maximum = 700.0f;

static bool ok(EngineResult result) {
    if(!rohr_error_check(result)) return true;
    fprintf(stderr, "error %d: %s\n", (int)result.result.error,
        rohr_error_message_get(result));
    return false;
}

static bool player_grounded_check(Entity player) {
    EntityContact contacts[PLAYER_CONTACT_LIMIT];
    size_t count = rohr_physics_contacts_get(
        player, contacts, PLAYER_CONTACT_LIMIT);

    for(size_t i = 0; i < count; i += 1)
        if(contacts[i].contact.detected && contacts[i].contact.normal.y < -0.5f)
            return true;
    return false;
}

static bool player_velocity_get(Entity player, Velocity *velocity) {
    EntityIndexResult index;
    if(velocity == NULL) return false;
    index = rohr_entity_index_get(player);
    if(rohr_error_check(index) || index.result.value >= velocities_pool.capacity ||
            !velocities_pool.used[index.result.value]) return false;
    *velocity = velocities[index.result.value];
    return true;
}

static bool player_speed_limit_apply(Entity player) {
    Velocity velocity;
    Velocity limited;
    if(!player_velocity_get(player, &velocity)) return false;
    limited = (Velocity){
        fmaxf(-player_horizontal_speed_maximum,
            fminf(player_horizontal_speed_maximum, velocity.x)),
        fmaxf(-player_vertical_speed_maximum,
            fminf(player_vertical_speed_maximum, velocity.y))
    };
    if(limited.x == velocity.x && limited.y == velocity.y) return true;
    return ok(rohr_physics_velocity_set(player, limited));
}

int main(void) {
    ProjectObjects objects = {0};
    ProjectViewports viewports = {0};
    bool jump_queued = false;

    if(!ok(rohr_directory_working_set(rohr_directory_base_get()))) return 1;
    if(!ok(rohr_engine_start()) || !ok(rohr_graphics_start())) goto fail;
    if(!ok(project_objects_create_all(&objects)) ||
            !ok(project_viewports_create(&viewports, &objects))) goto fail;

    while(true) {
        SDL_Event event;
        Tick ticks_advanced;
        InputAxis1DResult move;
        Velocity velocity;
        float move_axis;

        rohr_input_frame_begin();
        while((event = rohr_engine_event_poll()).type != 0)
            if(event.type == SDL_EVENT_QUIT) goto done;
        if(rohr_input_key_pressed_check(SDL_SCANCODE_ESCAPE)) break;

        if(rohr_input_action_button_pressed_check(
                objects.controllers.action_player_jump_2) &&
                player_grounded_check(objects.player_world.player))
            jump_queued = true;

        ticks_advanced = rohr_system_tick_update();
        if(ticks_advanced > 0) {
            move = rohr_input_action_axis_1d_get(
                objects.controllers.action_player_move_1);
            move_axis = rohr_error_check(move) ? 0.0f : move.result.value;
            if(!player_velocity_get(objects.player_world.player, &velocity))
                goto fail;
            if(move_axis != 0.0f &&
                    ((move_axis < 0.0f &&
                        velocity.x > -player_horizontal_speed_maximum) ||
                     (move_axis > 0.0f &&
                        velocity.x < player_horizontal_speed_maximum)) &&
                    !ok(rohr_physics_force_apply(
                        objects.player_world.player,
                        (Force){move_axis * player_move_force, 0.0f}))) goto fail;
            if(jump_queued && !ok(rohr_physics_force_apply(
                    objects.player_world.player,
                    (Force){0.0f, player_jump_force}))) goto fail;
            jump_queued = false;
        }

        if(!ok(rohr_physics_update(ticks_advanced)) ||
                !player_speed_limit_apply(objects.player_world.player)) goto fail;
        rohr_graphics_show();
    }

done:
    project_viewports_destroy(&viewports);
    project_objects_destroy_all(&objects);
    rohr_graphics_stop();
    rohr_engine_stop();
    return 0;
fail:
    fprintf(stderr, "Player controller example failed\n");
    project_viewports_destroy(&viewports);
    project_objects_destroy_all(&objects);
    rohr_graphics_stop();
    rohr_engine_stop();
    return 1;
}
